-- Relax attendance RLS to let any project member manage sessions and entries.
-- Generated by Codex on 2026-03-16

-- Attendance sessions
DROP POLICY IF EXISTS "Members manage sessions" ON public.attendance_sessions;
CREATE POLICY "Members manage sessions"
  ON public.attendance_sessions
  FOR ALL
  USING (public.is_project_member(project_id, auth.uid()))
  WITH CHECK (public.is_project_member(project_id, auth.uid()));

-- Attendance entries
DROP POLICY IF EXISTS "Members manage entries" ON public.attendance_entries;
CREATE POLICY "Members manage entries"
  ON public.attendance_entries
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.attendance_sessions s
      WHERE s.id = attendance_entries.session_id
        AND public.is_project_member(s.project_id, auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.attendance_sessions s
      WHERE s.id = attendance_entries.session_id
        AND public.is_project_member(s.project_id, auth.uid())
    )
  );
